import type { CompanyBreakdown, ThroatRole, WhyBottleneckOrNot } from "./types";
import type { CompanySeed } from "./mockData";

function why(
  scarce_resource: string,
  can_function_without: string,
  replaceability_1_to_3_years: string,
): WhyBottleneckOrNot {
  return { scarce_resource, can_function_without, replaceability_1_to_3_years };
}

function company(
  ticker: string,
  name: string,
  chain_position: string,
  throat_role: ThroatRole,
  sector_tags: string[],
  keywords: string[],
  why_bottleneck_or_not: WhyBottleneckOrNot,
  breakdown: Partial<CompanyBreakdown>,
): CompanySeed {
  return {
    ticker,
    name,
    chain_position,
    throat_role,
    sector_tags,
    keywords,
    why_bottleneck_or_not,
    breakdown,
  };
}

export const COMPANY_UNIVERSE: CompanySeed[] = [
  company(
    "NVDA",
    "NVIDIA",
    "AI Compute — accelerator allocation and CUDA stack",
    "CORE BOTTLENECK",
    ["Semiconductors", "AI Infrastructure", "Robotics"],
    ["gpu", "ai", "accelerator", "chip", "cuda", "compute", "data center"],
    why(
      "Controls scarce GPU allocation and the CUDA software stack for AI workloads.",
      "Large-scale AI training and inference cannot scale without NVIDIA-class accelerators today.",
      "AMD and custom ASICs reduce but do not remove dependence within 1–3 years.",
    ),
    {
      bottleneck_strength: 96,
      supply_chain_control: 94,
      replaceability: 14,
      industry_dependency: 92,
    },
  ),
  company(
    "AMD",
    "Advanced Micro Devices",
    "AI Compute — secondary GPU/CPU path",
    "STRATEGIC ENABLER",
    ["Semiconductors", "AI Infrastructure"],
    ["gpu", "cpu", "accelerator", "chip", "ai"],
    why(
      "Provides an alternative accelerator route but still consumes upstream fab and packaging capacity.",
      "Relieves single-vendor GPU pressure without controlling the primary allocation throat.",
      "Already substituting for NVIDIA in select workloads; share gains expected in 1–3 years.",
    ),
    { bottleneck_strength: 78, supply_chain_control: 72, replaceability: 42, industry_dependency: 80 },
  ),
  company(
    "AMAT",
    "Applied Materials",
    "Wafer Fab Equipment — deposition and materials",
    "STRATEGIC ENABLER",
    ["Semiconductors", "Materials"],
    ["wafer", "fab", "semiconductor", "deposition", "equipment"],
    why(
      "Owns critical deposition steps with long install-base lock-in at advanced fabs.",
      "Fab ramps slow without AMAT-class tools, but multiple WFE vendors share the chain.",
      "Tooling mix can shift across vendors over 2–3 years.",
    ),
    { bottleneck_strength: 86, supply_chain_control: 88, replaceability: 32, industry_dependency: 78 },
  ),
  company(
    "LRCX",
    "Lam Research",
    "Wafer Fab Equipment — etch systems",
    "STRATEGIC ENABLER",
    ["Semiconductors"],
    ["etch", "wafer", "fab", "semiconductor", "equipment"],
    why(
      "Etch capacity is concentrated and required for advanced 3D structures.",
      "Node transitions stall if etch throughput is unavailable.",
      "Partial dual-sourcing is feasible over a 2–3 year qualification cycle.",
    ),
    { bottleneck_strength: 84, supply_chain_control: 85, replaceability: 35, industry_dependency: 76 },
  ),
  company(
    "AVGO",
    "Broadcom",
    "Custom silicon and networking",
    "STRATEGIC ENABLER",
    ["Semiconductors", "AI Infrastructure"],
    ["asic", "networking", "custom", "chip", "ai"],
    why(
      "Important in custom AI ASIC and networking niches with design lock-in.",
      "Broader AI buildout proceeds without any single Broadcom SKU.",
      "Hyperscale programs can re-architect away from specific parts in 2–3 years.",
    ),
    { bottleneck_strength: 76, supply_chain_control: 74, replaceability: 38, industry_dependency: 70 },
  ),
  company(
    "ANET",
    "Arista Networks",
    "Networking fabric — AI cluster switching",
    "CORE BOTTLENECK",
    ["AI Infrastructure", "Data Centers"],
    ["network", "switch", "fabric", "data center", "ai cluster"],
    why(
      "High-radix switches are scarce for large AI fabrics once GPUs are installed.",
      "Cluster scale-out bandwidth can bind before power or cooling constraints.",
      "Switch vendors can be qualified on a 2–3 year migration path.",
    ),
    { bottleneck_strength: 82, supply_chain_control: 80, replaceability: 40, industry_dependency: 78 },
  ),
  company(
    "VRT",
    "Vertiv",
    "Power & thermal — liquid cooling and rack PDUs",
    "STRATEGIC ENABLER",
    ["AI Infrastructure", "Energy Storage"],
    ["power", "cooling", "thermal", "data center", "liquid"],
    why(
      "Liquid cooling and PDUs are required for dense AI racks but sourced from multiple vendors.",
      "Deployment slows without thermal capacity; it does not halt accelerator production.",
      "Facility vendors are interchangeable over 1–3 years with engineering lead time.",
    ),
    { bottleneck_strength: 74, supply_chain_control: 70, replaceability: 46, industry_dependency: 68 },
  ),
  company(
    "EQIX",
    "Equinix",
    "Colocation & interconnection",
    "PERIPHERAL EXPOSURE",
    ["AI Infrastructure", "Data Centers"],
    ["colocation", "data center", "interconnect"],
    why(
      "Floor space is a localized constraint, not an industry-wide scarce resource.",
      "AI buildout continues across multiple regions without a single operator.",
      "Site selection rotates among operators within 1–3 years.",
    ),
    { bottleneck_strength: 46, supply_chain_control: 42, replaceability: 74, industry_dependency: 38 },
  ),
  company(
    "MSFT",
    "Microsoft",
    "Cloud control plane — Azure, identity, Copilot",
    "CORE BOTTLENECK",
    ["Cloud Software", "AI Infrastructure", "Fintech", "Healthcare AI"],
    ["cloud", "azure", "identity", "platform", "saas", "copilot", "ai"],
    why(
      "Controls enterprise identity, Azure tenancy, and Copilot deployment paths.",
      "Large enterprises cannot migrate AI production workloads quickly off Microsoft gravity.",
      "Multi-cloud strategies reduce but do not eliminate dependence within 1–3 years.",
    ),
    { bottleneck_strength: 92, supply_chain_control: 90, replaceability: 18, industry_dependency: 94 },
  ),
  company(
    "CRM",
    "Salesforce",
    "Workflow applications — CRM data gravity",
    "DOWNSTREAM USER",
    ["Cloud Software", "Fintech"],
    ["crm", "saas", "workflow", "enterprise"],
    why(
      "CRM data gravity is account-level, not an industry-wide scarce AI resource.",
      "Infrastructure bottlenecks bind before CRM selection does.",
      "CRM alternatives are available within 1–3 years.",
    ),
    { bottleneck_strength: 48, supply_chain_control: 44, replaceability: 62, industry_dependency: 42 },
  ),
  company(
    "CRWD",
    "CrowdStrike",
    "Security platform — endpoint and identity layer",
    "STRATEGIC ENABLER",
    ["Cloud Software", "Defense Tech"],
    ["security", "endpoint", "zero trust", "platform"],
    why(
      "Endpoint agents are sticky for compliance but not scarce like cloud identity.",
      "Workloads can run with alternate EDR vendors after migration windows.",
      "Security vendor swaps are planned on 1–3 year enterprise cycles.",
    ),
    { bottleneck_strength: 62, supply_chain_control: 58, replaceability: 52, industry_dependency: 54 },
  ),
  company(
    "SNOW",
    "Snowflake",
    "Data platform — warehouse gravity",
    "PERIPHERAL EXPOSURE",
    ["Cloud Software", "Healthcare AI", "Fintech"],
    ["data", "warehouse", "analytics", "platform"],
    why(
      "Data warehouse layer is substitutable among cloud analytics platforms.",
      "AI compute and identity bottlenecks bind before warehouse selection.",
      "Analytics stack migration typically completes within 1–3 years.",
    ),
    { bottleneck_strength: 44, supply_chain_control: 40, replaceability: 66, industry_dependency: 38 },
  ),
  company(
    "ALB",
    "Albemarle",
    "Lithium & specialty materials — battery inputs",
    "CORE BOTTLENECK",
    ["Energy Storage", "Materials", "EV Batteries"],
    ["lithium", "battery", "ev", "energy storage", "materials", "cathode"],
    why(
      "Refined lithium and specialty chemicals are scarce inputs for battery scale-up.",
      "EV and grid storage buildouts slow when lithium conversion capacity is tight.",
      "New supply and chemistry shifts emerge over 2–3 years but remain constrained.",
    ),
    { bottleneck_strength: 84, supply_chain_control: 80, replaceability: 36, industry_dependency: 82 },
  ),
  company(
    "TSLA",
    "Tesla",
    "Battery integration — cells, packs, and EV platform",
    "STRATEGIC ENABLER",
    ["Automotive", "EV Batteries", "Robotics"],
    ["ev", "battery", "energy storage", "vehicle", "automotive", "car", "robotics"],
    why(
      "Integrates cells into packs and vehicles but does not control upstream lithium refining alone.",
      "EV industry continues with multiple OEM paths if Tesla-specific supply tightens.",
      "Alternative OEM and chemistry routes expand within 1–3 years.",
    ),
    { bottleneck_strength: 72, supply_chain_control: 68, replaceability: 44, industry_dependency: 74 },
  ),
  company(
    "CCJ",
    "Cameco",
    "Nuclear fuel — uranium supply",
    "CORE BOTTLENECK",
    ["Nuclear Energy", "Materials"],
    ["uranium", "nuclear", "fuel", "reactor", "energy"],
    why(
      "Qualified uranium supply is concentrated and gates reactor fuel cycles.",
      "New nuclear capacity cannot ramp without secured fuel contracts.",
      "Alternative suppliers exist but qualification and contracting take years.",
    ),
    { bottleneck_strength: 86, supply_chain_control: 82, replaceability: 28, industry_dependency: 80 },
  ),
  company(
    "NEE",
    "NextEra Energy",
    "Utility-scale deployment — grid and project execution",
    "STRATEGIC ENABLER",
    ["Nuclear Energy", "Energy Storage"],
    ["utility", "grid", "nuclear", "power", "renewable"],
    why(
      "Important for project execution and offtake but not a single-source fuel choke.",
      "Power projects proceed across multiple utilities and regions.",
      "Developer and utility mix shifts over multi-year project cycles.",
    ),
    { bottleneck_strength: 58, supply_chain_control: 54, replaceability: 56, industry_dependency: 60 },
  ),
  company(
    "LMT",
    "Lockheed Martin",
    "Defense platforms — aerospace and mission systems",
    "CORE BOTTLENECK",
    ["Defense Tech", "Aerospace"],
    ["defense", "military", "aerospace", "missile", "security"],
    why(
      "Long-cycle defense platforms and cleared supply chains are hard to replicate quickly.",
      "Mission-critical programs depend on prime integrators with security clearance depth.",
      "Competition exists but reallocation across primes requires years of re-contracting.",
    ),
    { bottleneck_strength: 80, supply_chain_control: 78, replaceability: 34, industry_dependency: 76 },
  ),
  company(
    "RTX",
    "RTX Corporation",
    "Aerospace engines and defense subsystems",
    "STRATEGIC ENABLER",
    ["Defense Tech", "Aerospace"],
    ["defense", "engine", "aerospace", "subsystem"],
    why(
      "Critical in propulsion and avionics subsystems with qualification barriers.",
      "Defense supply chains can reroute among qualified subsystem vendors over time.",
      "Dual sourcing is possible on 2–3 year re-qualification horizons.",
    ),
    { bottleneck_strength: 74, supply_chain_control: 72, replaceability: 40, industry_dependency: 70 },
  ),
  company(
    "PLTR",
    "Palantir",
    "Defense & enterprise AI platforms",
    "STRATEGIC ENABLER",
    ["Defense Tech", "Healthcare AI", "AI Infrastructure"],
    ["defense", "ai", "platform", "data", "government"],
    why(
      "Embedded in government and enterprise AI workflows with deployment friction.",
      "Does not control raw compute allocation or classified hardware manufacturing.",
      "Platform competition increases within 1–3 years in commercial segments.",
    ),
    { bottleneck_strength: 66, supply_chain_control: 62, replaceability: 48, industry_dependency: 64 },
  ),
  company(
    "ISRG",
    "Intuitive Surgical",
    "Surgical robotics systems",
    "CORE BOTTLENECK",
    ["Robotics", "Healthcare AI"],
    ["robotics", "surgical", "healthcare", "medical device", "automation"],
    why(
      "Installed base and consumables create a durable choke in robotic surgery niches.",
      "Hospital robotic surgery programs are hard to swap without capital and training cycles.",
      "Competitors emerge but conversion timelines run 2–3+ years.",
    ),
    { bottleneck_strength: 82, supply_chain_control: 78, replaceability: 32, industry_dependency: 74 },
  ),
  company(
    "ROK",
    "Rockwell Automation",
    "Industrial automation and factory control",
    "STRATEGIC ENABLER",
    ["Robotics", "Industrial Automation"],
    ["robotics", "automation", "factory", "industrial", "control"],
    why(
      "Factory control layers are sticky but fragmented across automation vendors.",
      "Manufacturing continues with multiple automation stacks.",
      "Vendor rotation is feasible over 1–3 year retrofit cycles.",
    ),
    { bottleneck_strength: 68, supply_chain_control: 64, replaceability: 50, industry_dependency: 62 },
  ),
  company(
    "TER",
    "Teradyne",
    "Robotics & test — cobots and automation hardware",
    "STRATEGIC ENABLER",
    ["Robotics", "Semiconductors"],
    ["robotics", "cobot", "test", "automation"],
    why(
      "Important in cobots and test equipment niches without single-industry choke power.",
      "Automation projects can choose among robot and test vendors.",
      "Hardware substitution is possible within 1–3 years.",
    ),
    { bottleneck_strength: 60, supply_chain_control: 56, replaceability: 54, industry_dependency: 58 },
  ),
  company(
    "UNH",
    "UnitedHealth Group",
    "Healthcare platform — payer and care delivery scale",
    "STRATEGIC ENABLER",
    ["Healthcare AI", "Fintech"],
    ["healthcare", "payer", "insurance", "clinical", "ai"],
    why(
      "Massive claims and provider network scale create switching friction.",
      "Does not control GPU supply or core AI silicon bottlenecks.",
      "Payer competition and regulation shift share over multi-year cycles.",
    ),
    { bottleneck_strength: 64, supply_chain_control: 66, replaceability: 46, industry_dependency: 68 },
  ),
  company(
    "VEEV",
    "Veeva Systems",
    "Life sciences cloud — regulated workflow software",
    "STRATEGIC ENABLER",
    ["Healthcare AI", "Cloud Software"],
    ["healthcare", "pharma", "life sciences", "cloud", "compliance"],
    why(
      "Regulated workflow lock-in in pharma commercial and clinical clouds.",
      "Drug discovery compute bottlenecks sit upstream of Veeva-specific constraints.",
      "Migration is painful but feasible over 2–3 year enterprise cycles.",
    ),
    { bottleneck_strength: 58, supply_chain_control: 60, replaceability: 44, industry_dependency: 56 },
  ),
  company(
    "V",
    "Visa",
    "Payments network — transaction rails",
    "CORE BOTTLENECK",
    ["Fintech", "Cloud Software"],
    ["fintech", "payments", "network", "transaction", "banking"],
    why(
      "Global payment rails and network effects create a digital choke point for money movement.",
      "Consumer and merchant payment flows depend on incumbent network acceptance.",
      "Alternative rails and real-time payment schemes grow over 1–3 years but remain partial.",
    ),
    { bottleneck_strength: 88, supply_chain_control: 86, replaceability: 26, industry_dependency: 90 },
  ),
  company(
    "MA",
    "Mastercard",
    "Payments network — cross-border rails",
    "STRATEGIC ENABLER",
    ["Fintech"],
    ["fintech", "payments", "network", "cross-border"],
    why(
      "Parallel global network with similar choke characteristics to Visa.",
      "Merchants rarely depend on a single network exclusively.",
      "Competitive routing and local schemes expand within 1–3 years.",
    ),
    { bottleneck_strength: 84, supply_chain_control: 82, replaceability: 30, industry_dependency: 86 },
  ),
  company(
    "COIN",
    "Coinbase",
    "Crypto exchange & custody — digital asset rails",
    "DOWNSTREAM USER",
    ["Fintech"],
    ["crypto", "exchange", "fintech", "digital assets"],
    why(
      "Exchange liquidity matters for crypto but not for broader fintech payment rails.",
      "Traditional fintech and banking flows do not require Coinbase specifically.",
      "Exchange share is highly substitutable within 1–2 years.",
    ),
    { bottleneck_strength: 52, supply_chain_control: 48, replaceability: 68, industry_dependency: 40 },
  ),
  company(
    "ORCL",
    "Oracle",
    "Database & cloud infrastructure anchor",
    "STRATEGIC ENABLER",
    ["Cloud Software", "Healthcare AI", "Fintech"],
    ["database", "cloud", "enterprise", "oci"],
    why(
      "Database estates create migration friction in Oracle-heavy enterprises.",
      "General AI deployment does not require Oracle-specific control planes.",
      "Database and cloud substitution is painful but feasible over 2–3 years.",
    ),
    { bottleneck_strength: 72, supply_chain_control: 70, replaceability: 44, industry_dependency: 68 },
  ),
  company(
    "SMCI",
    "Super Micro Computer",
    "AI rack integration — ODM supply",
    "DOWNSTREAM USER",
    ["AI Infrastructure"],
    ["server", "rack", "odm", "ai", "integration"],
    why(
      "Integrates upstream silicon into racks without owning scarce compute allocation.",
      "Other ODMs and hyperscale self-builds can absorb integration demand.",
      "ODM share shifts within 1–2 years.",
    ),
    { bottleneck_strength: 62, supply_chain_control: 55, replaceability: 58, industry_dependency: 66 },
  ),
  company(
    "TSM",
    "Taiwan Semiconductor",
    "Foundry — advanced-node wafer starts",
    "CORE BOTTLENECK",
    ["Semiconductors"],
    ["foundry", "wafer", "semiconductor", "fab", "chip", "tsmc"],
    why(
      "Leading-edge wafer starts are concentrated and gate every fabless design ramp.",
      "Advanced AI and mobile silicon cannot scale without foundry allocation.",
      "Geographic diversification progresses but remains constrained over 1–3 years.",
    ),
    { bottleneck_strength: 94, supply_chain_control: 92, replaceability: 18, industry_dependency: 90 },
  ),
  company(
    "ASML",
    "ASML Holding",
    "Lithography — EUV systems",
    "CORE BOTTLENECK",
    ["Semiconductors"],
    ["lithography", "euv", "semiconductor", "wafer", "equipment"],
    why(
      "EUV lithography systems are effectively single-source for leading nodes.",
      "New advanced fabs cannot ramp without ASML-class lithography throughput.",
      "Alternative patterning routes remain immature within a 1–3 year horizon.",
    ),
    { bottleneck_strength: 92, supply_chain_control: 90, replaceability: 16, industry_dependency: 88 },
  ),
  company(
    "AMZN",
    "Amazon",
    "Hyperscale cloud — AWS and AI workloads",
    "STRATEGIC ENABLER",
    ["AI Infrastructure", "Cloud Software", "Data Centers"],
    ["aws", "cloud", "hyperscale", "ai", "data center", "amazon"],
    why(
      "Controls AWS tenancy and AI service deployment for a large share of cloud compute.",
      "Enterprise AI workloads increasingly route through hyperscale control planes.",
      "Multi-cloud adoption reduces but does not remove AWS gravity within 1–3 years.",
    ),
    { bottleneck_strength: 86, supply_chain_control: 84, replaceability: 28, industry_dependency: 88 },
  ),
  company(
    "GOOGL",
    "Alphabet",
    "Hyperscale cloud — GCP and Gemini stack",
    "STRATEGIC ENABLER",
    ["AI Infrastructure", "Cloud Software", "Data Centers"],
    ["google", "gcp", "cloud", "ai", "gemini", "hyperscale"],
    why(
      "Owns GCP infrastructure and model serving paths for large AI deployments.",
      "Search and cloud AI products depend on internal accelerator and TPU allocation.",
      "Competing hyperscalers provide alternatives over 1–3 years with migration cost.",
    ),
    { bottleneck_strength: 84, supply_chain_control: 82, replaceability: 30, industry_dependency: 86 },
  ),
  company(
    "LLY",
    "Eli Lilly",
    "Large-cap pharma — GLP-1 and pipeline scale",
    "CORE BOTTLENECK",
    ["Life Sciences", "Healthcare AI"],
    ["pharma", "biotech", "drug", "therapeutic", "clinical", "pipeline"],
    why(
      "Manufacturing and commercial scale for blockbuster therapies create supply choke points.",
      "Hospital and payer formularies depend on availability of leading drug franchises.",
      "Competitor pipelines emerge over 2–3 years but capacity ramps remain tight.",
    ),
    { bottleneck_strength: 82, supply_chain_control: 78, replaceability: 34, industry_dependency: 80 },
  ),
  company(
    "PFE",
    "Pfizer",
    "Large-cap pharma — global commercialization",
    "STRATEGIC ENABLER",
    ["Life Sciences", "Healthcare AI"],
    ["pharma", "biotech", "drug", "vaccine", "clinical"],
    why(
      "Global distribution and manufacturing networks matter for drug availability.",
      "Individual therapies are substitutable across large pharma peers over time.",
      "Portfolio mix shifts among majors within 1–3 year patent cycles.",
    ),
    { bottleneck_strength: 72, supply_chain_control: 70, replaceability: 42, industry_dependency: 74 },
  ),
  company(
    "MRK",
    "Merck",
    "Large-cap pharma — oncology and vaccines",
    "STRATEGIC ENABLER",
    ["Life Sciences", "Healthcare AI"],
    ["pharma", "biotech", "drug", "oncology", "vaccine"],
    why(
      "Key oncology franchises create therapeutic bottlenecks in specific indications.",
      "Broader biotech ecosystem continues with multiple pharma pathways.",
      "Biosimilar and competitor entry expands within 2–3 years.",
    ),
    { bottleneck_strength: 74, supply_chain_control: 72, replaceability: 40, industry_dependency: 72 },
  ),
  company(
    "XOM",
    "Exxon Mobil",
    "Integrated major — upstream and refining",
    "CORE BOTTLENECK",
    ["Oil & Gas", "Energy"],
    ["oil", "gas", "petroleum", "upstream", "refining", "energy"],
    why(
      "Reserve base and capital allocation discipline shape global hydrocarbon supply.",
      "Downstream fuel markets depend on integrated majors for marginal barrels.",
      "OPEC+ and alternative supply respond over multi-year cycles, not months.",
    ),
    { bottleneck_strength: 80, supply_chain_control: 78, replaceability: 36, industry_dependency: 76 },
  ),
  company(
    "CVX",
    "Chevron",
    "Integrated major — upstream production",
    "STRATEGIC ENABLER",
    ["Oil & Gas", "Energy"],
    ["oil", "gas", "petroleum", "upstream", "energy", "chevron"],
    why(
      "Major producer with leverage to short-cycle shale and long-cycle projects.",
      "Global supply continues if any single major tightens capex.",
      "Portfolio rebalancing across majors occurs over 1–3 year investment cycles.",
    ),
    { bottleneck_strength: 76, supply_chain_control: 74, replaceability: 40, industry_dependency: 72 },
  ),
  company(
    "SLB",
    "SLB (Schlumberger)",
    "Oilfield services — drilling and reservoir",
    "CORE BOTTLENECK",
    ["Oil & Gas", "Energy"],
    ["oilfield", "drilling", "services", "upstream", "schlumberger", "slb"],
    why(
      "Drilling and reservoir services capacity binds short-cycle production growth.",
      "New wells and field redevelopments stall when service intensity is unavailable.",
      "Competing service vendors exist but reallocation takes 1–2 years.",
    ),
    { bottleneck_strength: 78, supply_chain_control: 76, replaceability: 38, industry_dependency: 74 },
  ),
  company(
    "BYDDY",
    "BYD (ADR)",
    "EV OEM — cells, packs, and CATL-chain exposure",
    "STRATEGIC ENABLER",
    ["EV Batteries", "Energy Storage", "Automotive", "Robotics"],
    ["byd", "catl", "ev", "battery", "cell", "vehicle", "automotive", "car", "china"],
    why(
      "Vertically integrated EV and battery OEM with exposure to LFP supply chains including CATL ecosystem partners.",
      "Global EV production continues with multiple OEM paths if BYD-specific supply tightens.",
      "Regional OEM and chemistry diversification expands within 1–3 years.",
    ),
    { bottleneck_strength: 76, supply_chain_control: 72, replaceability: 40, industry_dependency: 78 },
  ),
  company(
    "GM",
    "General Motors",
    "OEM assembly — North America vehicle platforms",
    "STRATEGIC ENABLER",
    ["Automotive", "EV Batteries"],
    ["automotive", "auto", "car", "vehicle", "oem", "ev", "assembly"],
    why(
      "Large-scale vehicle assembly and platform decisions shape regional auto supply chains.",
      "Industry continues with multiple OEMs if any single Detroit platform slows.",
      "Competitive model cycles rebalance share within 1–3 years.",
    ),
    { bottleneck_strength: 68, supply_chain_control: 64, replaceability: 48, industry_dependency: 72 },
  ),
  company(
    "F",
    "Ford Motor",
    "OEM assembly — trucks and EV transition",
    "STRATEGIC ENABLER",
    ["Automotive", "EV Batteries"],
    ["automotive", "auto", "car", "vehicle", "oem", "truck", "ev"],
    why(
      "Truck and SUV mix plus EV ramp influence Tier-1 demand and battery allocation.",
      "Auto production persists across competing OEM footprints.",
      "Platform shifts and supplier re-bids occur over 2–3 year cycles.",
    ),
    { bottleneck_strength: 66, supply_chain_control: 62, replaceability: 50, industry_dependency: 70 },
  ),
  company(
    "APTV",
    "Aptiv",
    "Tier-1 — automotive electronics and wiring",
    "CORE BOTTLENECK",
    ["Automotive"],
    ["automotive", "auto", "tier-1", "vehicle", "electronics", "oem", "car"],
    why(
      "High-voltage architecture and ADAS electronics are qualified per platform with long design-in cycles.",
      "OEM launches stall when Tier-1 electronics capacity or software stacks slip.",
      "Dual sourcing is possible but requires 2–3 year re-qualification.",
    ),
    { bottleneck_strength: 78, supply_chain_control: 74, replaceability: 38, industry_dependency: 76 },
  ),
];
