import type { CompanySeed } from "./mockData";
import { company, why } from "./companyUniverseHelpers";

/** Niche / high-potential names — space, quantum, critical minerals, EDA, cyber, etc. */
export const COMPANY_UNIVERSE_NICHE: CompanySeed[] = [
  // —— Space & satellite ——
  company(
    "RKLB",
    "Rocket Lab",
    "Launch — small satellite dedicated rideshare",
    "CORE BOTTLENECK",
    ["Space", "Defense", "Robotics"],
    ["space", "satellite", "launch", "rocket", "orbit", "aerospace", "defense"],
    why(
      "Qualified launch slots and photon bus integration are scarce for LEO constellation deployers.",
      "Large constellations can delay missions if small-lift capacity or mission integration slips.",
      "Alternative launchers exist but re-qualification and schedule risk take 1–3 years.",
    ),
    { bottleneck_strength: 84, supply_chain_control: 80, replaceability: 32, industry_dependency: 78 },
  ),
  company(
    "ASTS",
    "AST SpaceMobile",
    "Satellite — direct-to-cell broadband constellation",
    "STRATEGIC ENABLER",
    ["Space", "Telecom"],
    ["space", "satellite", "telecom", "5g", "broadband", "constellation", "cellular"],
    why(
      "Owns phased-array satellite architecture tied to carrier partnerships for direct-to-phone coverage.",
      "Regional mobile expansion can proceed without it, but gap-coverage economics depend on successful deployment.",
      "Competing LEO architectures could substitute in some markets over 2–3 years.",
    ),
    { bottleneck_strength: 76, supply_chain_control: 70, replaceability: 42, industry_dependency: 72 },
  ),
  company(
    "LUNR",
    "Intuitive Machines",
    "Space — lunar lander and surface delivery",
    "STRATEGIC ENABLER",
    ["Space", "Defense"],
    ["space", "lunar", "moon", "lander", "nasa", "aerospace", "defense"],
    why(
      "Controls qualified lunar delivery milestones with limited commercial lander alternatives.",
      "Broader space economy continues if lunar programs slip, but Artemis-linked timelines tighten.",
      "Additional lander entrants may diversify supply after initial qualification cycles.",
    ),
    { bottleneck_strength: 72, supply_chain_control: 68, replaceability: 45, industry_dependency: 65 },
  ),
  // —— Quantum ——
  company(
    "IONQ",
    "IonQ",
    "Quantum — trapped-ion compute systems",
    "CORE BOTTLENECK",
    ["Quantum Computing", "Platform Software"],
    ["quantum", "computing", "qubit", "cloud", "research", "cryptography", "simulation"],
    why(
      "Gate-based quantum systems with cloud access remain scarce for enterprise and government pilots.",
      "Classical HPC covers most workloads; quantum advantage niches depend on available qubit hours.",
      "Competing modalities (superconducting, photonic) may broaden choice over 2–3 years.",
    ),
    { bottleneck_strength: 82, supply_chain_control: 78, replaceability: 35, industry_dependency: 70 },
  ),
  company(
    "RGTI",
    "Rigetti Computing",
    "Quantum — superconducting QPUs and Fab",
    "STRATEGIC ENABLER",
    ["Quantum Computing"],
    ["quantum", "superconducting", "qpu", "fab", "computing", "research"],
    why(
      "Vertical QPU + fab integration creates specialized supply for hybrid quantum-classical stacks.",
      "Industry can wait on broad quantum utility, but research programs need allocated machine time.",
      "Other superconducting vendors and cloud partners reduce single-vendor dependence over time.",
    ),
    { bottleneck_strength: 74, supply_chain_control: 72, replaceability: 40, industry_dependency: 66 },
  ),
  company(
    "QBTS",
    "D-Wave Quantum",
    "Quantum — annealing optimization systems",
    "STRATEGIC ENABLER",
    ["Quantum Computing"],
    ["quantum", "annealing", "optimization", "logistics", "computing", "research"],
    why(
      "Owns annealing architecture for combinatorial optimization workloads hard to map on gate systems.",
      "Most optimization problems still run classically; niche adopters depend on proven quantum speedups.",
      "Gate-based and classical solvers compete for overlapping problem sets.",
    ),
    { bottleneck_strength: 70, supply_chain_control: 68, replaceability: 44, industry_dependency: 62 },
  ),
  // —— Nuclear & uranium ——
  company(
    "UEC",
    "Uranium Energy",
    "Uranium — U.S. ISR mining and fuel cycle feed",
    "CORE BOTTLENECK",
    ["Nuclear", "Energy Materials"],
    ["uranium", "nuclear", "fuel", "mining", "reactor", "enrichment", "energy"],
    why(
      "Western reactor restarts depend on permitted uranium supply outside concentrated jurisdictions.",
      "Plants can draw inventory buffers, but sustained undersupply tightens conversion and enrichment chains.",
      "New mines and contracts take years; substitution is limited for certified fuel paths.",
    ),
    { bottleneck_strength: 86, supply_chain_control: 80, replaceability: 26, industry_dependency: 84 },
  ),
  company(
    "LEU",
    "Centrus Energy",
    "Nuclear — HALEU enrichment and advanced fuels",
    "CORE BOTTLENECK",
    ["Nuclear", "Defense"],
    ["uranium", "enrichment", "haleu", "nuclear", "smr", "reactor", "fuel"],
    why(
      "Licensed HALEU enrichment capacity is a choke point for advanced reactors and defense micro-reactors.",
      "Conventional LEU cycles continue for legacy fleets; next-gen designs stall without HALEU supply.",
      "Additional enrichment capacity is policy- and capital-intensive over a 3+ year horizon.",
    ),
    { bottleneck_strength: 90, supply_chain_control: 88, replaceability: 22, industry_dependency: 86 },
  ),
  company(
    "OKLO",
    "Oklo",
    "Nuclear — fast-reactor SMR and fuel recycling",
    "STRATEGIC ENABLER",
    ["Nuclear", "AI Infrastructure"],
    ["nuclear", "smr", "reactor", "power", "data center", "microgrid", "energy"],
    why(
      "Targets behind-the-meter power for AI and remote loads with novel licensing pathway.",
      "Grid can supply data centers without Oklo, but siting and speed advantages matter for niche deployments.",
      "Competing SMR vendors and grid interconnect may substitute in 2–3 years if licensed.",
    ),
    { bottleneck_strength: 78, supply_chain_control: 72, replaceability: 38, industry_dependency: 74 },
  ),
  // —— Critical minerals ——
  company(
    "MP",
    "MP Materials",
    "Rare earth — Mountain Pass mining and magnet supply chain",
    "CORE BOTTLENECK",
    ["Energy Materials", "Defense", "EV Batteries"],
    ["rare earth", "magnet", "neodymium", "mining", "ev", "defense", "material"],
    why(
      "Western magnet supply chains depend on separated rare earth oxide capacity and offtake.",
      "EV and defense motors can defer ramps but cannot eliminate magnet inputs long term.",
      "China-dominated refining limits near-term substitution; new capacity takes years.",
    ),
    { bottleneck_strength: 88, supply_chain_control: 84, replaceability: 24, industry_dependency: 85 },
  ),
  company(
    "LAC",
    "Lithium Americas",
    "Lithium — Thacker Pass and Americas resource base",
    "STRATEGIC ENABLER",
    ["EV Batteries", "Energy Materials"],
    ["lithium", "battery", "mining", "ev", "cathode", "material", "energy storage"],
    why(
      "Large-scale U.S. lithium resource underpins domestic cathode and cell capacity plans.",
      "Battery supply chains can import lithium chemicals, but IRA-linked sourcing favors domestic feed.",
      "Alternative brine and hard-rock projects diversify over 2–3 years.",
    ),
    { bottleneck_strength: 80, supply_chain_control: 74, replaceability: 36, industry_dependency: 82 },
  ),
  company(
    "FCX",
    "Freeport-McMoRan",
    "Copper — global mining and concentrate supply",
    "CORE BOTTLENECK",
    ["Energy Materials", "AI Infrastructure", "EV Batteries"],
    ["copper", "mining", "electrification", "grid", "data center", "ev", "material"],
    why(
      "Copper concentrate supply constrains electrification, grid build-out, and AI power infrastructure.",
      "Short-term substitution is limited; designs can defer but not eliminate copper intensity.",
      "New mine ramps are multi-year; scrap and thrifting only partially offset.",
    ),
    { bottleneck_strength: 87, supply_chain_control: 82, replaceability: 28, industry_dependency: 88 },
  ),
  company(
    "CF",
    "CF Industries",
    "Fertilizer — nitrogen production and ammonia",
    "CORE BOTTLENECK",
    ["Energy Materials", "Agriculture"],
    ["fertilizer", "ammonia", "nitrogen", "agriculture", "hydrogen", "chemical", "food"],
    why(
      "Nitrogen fertilizer capacity ties to natural gas feed and global food production stability.",
      "Farmers can adjust application rates briefly, but crop yields depend on reliable nitrogen supply.",
      "Import parity and new capacity shift share over 1–3 seasons, not instantly.",
    ),
    { bottleneck_strength: 82, supply_chain_control: 78, replaceability: 30, industry_dependency: 86 },
  ),
  // —— Grid, solar, power ——
  company(
    "GEV",
    "GE Vernova",
    "Power — gas turbines, grid equipment, wind",
    "CORE BOTTLENECK",
    ["AI Infrastructure", "Energy Materials"],
    ["grid", "power", "turbine", "transmission", "data center", "electrification", "utility"],
    why(
      "Gas turbine and grid equipment backlogs gate utility and hyperscale power delivery timelines.",
      "Loads can queue for interconnect, but AI clusters cannot energize without transformer and turbine slots.",
      "Competing OEMs add capacity but lead times remain extended 2–3 years.",
    ),
    { bottleneck_strength: 85, supply_chain_control: 80, replaceability: 32, industry_dependency: 84 },
  ),
  company(
    "ENPH",
    "Enphase Energy",
    "Solar — microinverter and home energy management",
    "STRATEGIC ENABLER",
    ["Solar", "Energy Materials"],
    ["solar", "microinverter", "renewable", "residential", "energy", "storage", "grid"],
    why(
      "Controls module-level inverter architecture with installer channel lock-in in residential solar.",
      "Solar deployments continue with string inverters, but premium segments favor Enphase ecosystems.",
      "Competing inverter platforms gain share in cycles of 2–3 years.",
    ),
    { bottleneck_strength: 74, supply_chain_control: 76, replaceability: 40, industry_dependency: 70 },
  ),
  company(
    "FSLR",
    "First Solar",
    "Solar — thin-film module manufacturing",
    "STRATEGIC ENABLER",
    ["Solar", "Energy Materials"],
    ["solar", "module", "utility scale", "renewable", "energy", "manufacturing"],
    why(
      "CdTe module capacity and domestic manufacturing footprint support utility-scale PPAs.",
      "Projects can source polysilicon modules instead, but policy and LCOE drive vendor mix.",
      "Polysilicon capacity expansions compete on price over 2–3 years.",
    ),
    { bottleneck_strength: 76, supply_chain_control: 74, replaceability: 38, industry_dependency: 72 },
  ),
  company(
    "ETN",
    "Eaton",
    "Electrical — power distribution and data center PDUs",
    "STRATEGIC ENABLER",
    ["AI Infrastructure", "Robotics"],
    ["electrical", "power", "distribution", "data center", "pdu", "grid", "electrification"],
    why(
      "Electrical gear and power management SKUs are allocation-sensitive for data center and industrial builds.",
      "Facilities can delay phases, but energized racks require qualified switchgear supply.",
      "Peer electrical OEMs expand capacity over multi-year cycles.",
    ),
    { bottleneck_strength: 78, supply_chain_control: 76, replaceability: 36, industry_dependency: 80 },
  ),
  // —— Cyber & cloud observability ——
  company(
    "ZS",
    "Zscaler",
    "Cybersecurity — zero-trust network access",
    "STRATEGIC ENABLER",
    ["Cybersecurity", "Platform Software"],
    ["cybersecurity", "zero trust", "security", "cloud", "network", "saas", "enterprise"],
    why(
      "Zero-trust architecture consolidates secure access with high migration friction once deployed.",
      "Enterprises can run legacy VPN stacks, but cloud-first policies push Zscaler adoption.",
      "Competing SASE platforms substitute over renewal cycles.",
    ),
    { bottleneck_strength: 73, supply_chain_control: 75, replaceability: 41, industry_dependency: 68 },
  ),
  company(
    "FTNT",
    "Fortinet",
    "Cybersecurity — unified network security appliances",
    "STRATEGIC ENABLER",
    ["Cybersecurity", "AI Infrastructure"],
    ["cybersecurity", "firewall", "security", "network", "enterprise", "hardware"],
    why(
      "Integrated appliance + software stack captures mid-market and service-provider security spend.",
      "Networks operate with mixed vendors, but Fortinet share reflects cost-performance lock-in.",
      "Cloud-native security displaces some appliance growth over time.",
    ),
    { bottleneck_strength: 72, supply_chain_control: 74, replaceability: 42, industry_dependency: 67 },
  ),
  company(
    "NET",
    "Cloudflare",
    "Edge cloud — CDN, security, and developer platform",
    "STRATEGIC ENABLER",
    ["Cybersecurity", "Platform Software", "AI Infrastructure"],
    ["edge", "cloud", "cdn", "security", "network", "saas", "developer", "ai"],
    why(
      "Global edge network underpins latency-sensitive apps and DDoS mitigation at scale.",
      "Sites can use hyperscaler CDN alternatives, but unified edge+security reduces vendor sprawl.",
      "Hyperscalers and Akamai compete for overlapping workloads.",
    ),
    { bottleneck_strength: 75, supply_chain_control: 78, replaceability: 39, industry_dependency: 71 },
  ),
  company(
    "DDOG",
    "Datadog",
    "Observability — metrics, logs, and APM platform",
    "STRATEGIC ENABLER",
    ["Platform Software", "AI Infrastructure"],
    ["observability", "monitoring", "cloud", "saas", "devops", "apm", "software"],
    why(
      "Becomes default observability layer for cloud-native stacks with integration breadth.",
      "Engineering orgs can stitch open-source tools, but enterprise standardization favors Datadog.",
      "Splunk, Grafana Cloud, and hyperscaler native tools compete in 2–3 year bake-offs.",
    ),
    { bottleneck_strength: 71, supply_chain_control: 73, replaceability: 43, industry_dependency: 69 },
  ),
  company(
    "MDB",
    "MongoDB",
    "Database — document model and Atlas cloud",
    "STRATEGIC ENABLER",
    ["Platform Software"],
    ["database", "cloud", "saas", "developer", "software", "data", "platform"],
    why(
      "Document database model embedded in modern app stacks with Atlas consumption growth.",
      "Relational and other NoSQL stores substitute for greenfield choices.",
      "Cloud provider managed services compete on price over time.",
    ),
    { bottleneck_strength: 70, supply_chain_control: 72, replaceability: 44, industry_dependency: 67 },
  ),
  // —— Semi tools & photonics ——
  company(
    "SNPS",
    "Synopsys",
    "EDA — chip design sign-off and IP",
    "CORE BOTTLENECK",
    ["Semiconductors", "AI Infrastructure"],
    ["eda", "chip design", "semiconductor", "ip", "software", "signoff", "advanced node"],
    why(
      "Advanced-node tape-outs depend on Synopsys tool chains and interface IP qualifications.",
      "Chips cannot reach production without EDA closure; duopoly structure limits substitution.",
      "Cadence overlap provides partial alternative over long migration cycles.",
    ),
    { bottleneck_strength: 92, supply_chain_control: 90, replaceability: 18, industry_dependency: 90 },
  ),
  company(
    "CDNS",
    "Cadence Design Systems",
    "EDA — analog/mixed-signal and systems design",
    "CORE BOTTLENECK",
    ["Semiconductors"],
    ["eda", "cadence", "chip design", "semiconductor", "software", "analog", "packaging"],
    why(
      "Co-duopoly in EDA with deep entanglement in analog, packaging, and systems workflows.",
      "Design teams cannot easily swap tool flows mid-program without schedule risk.",
      "Synopsys and internal tools partially substitute over multi-year transitions.",
    ),
    { bottleneck_strength: 91, supply_chain_control: 89, replaceability: 19, industry_dependency: 89 },
  ),
  company(
    "KLAC",
    "KLA Corporation",
    "Semicap — process control and inspection",
    "STRATEGIC ENABLER",
    ["Semiconductors"],
    ["semiconductor", "inspection", "metrology", "wfe", "fab", "yield", "equipment"],
    why(
      "Inspection intensity rises with advanced nodes; KLA tools gate yield learning curves.",
      "Fabs can run at lower yields temporarily, but economics require metrology allocation.",
      "Peer inspection vendors share segments but leadership persists in key layers.",
    ),
    { bottleneck_strength: 86, supply_chain_control: 88, replaceability: 30, industry_dependency: 84 },
  ),
  company(
    "COHR",
    "Coherent",
    "Photonics — lasers for industrial and datacom",
    "STRATEGIC ENABLER",
    ["Semiconductors", "AI Infrastructure"],
    ["photonics", "laser", "optical", "datacom", "industrial", "semiconductor", "network"],
    why(
      "High-power lasers and optical components constrain EV battery, industrial, and AI interconnect builds.",
      "Applications can redesign around optics shortages with delays.",
      "Alternative laser suppliers qualify over 1–3 year design cycles.",
    ),
    { bottleneck_strength: 79, supply_chain_control: 76, replaceability: 35, industry_dependency: 77 },
  ),
  company(
    "CIEN",
    "Ciena",
    "Optical networking — metro and long-haul transport",
    "CORE BOTTLENECK",
    ["AI Infrastructure", "Telecom"],
    ["optical", "network", "telecom", "data center", "fiber", "transport", "bandwidth"],
    why(
      "Optical transport capacity bottlenecks AI cluster east-west traffic and carrier backhaul upgrades.",
      "Traffic can buffer on existing layers briefly, but 800G cycles require new optical deployments.",
      "Nokia and Infinera compete but lead times remain tight industry-wide.",
    ),
    { bottleneck_strength: 83, supply_chain_control: 80, replaceability: 33, industry_dependency: 81 },
  ),
  // —— Biotech & medtech ——
  company(
    "MRNA",
    "Moderna",
    "Biotech — mRNA platform and vaccine pipeline",
    "STRATEGIC ENABLER",
    ["Biotech", "Healthcare"],
    ["mrna", "biotech", "vaccine", "pharma", "platform", "clinical", "therapeutic"],
    why(
      "mRNA manufacturing know-how and regulatory experience create platform optionality beyond COVID.",
      "Healthcare continues with traditional modalities if mRNA pipelines slip.",
      "Competing mRNA and protein platforms substitute indication-by-indication.",
    ),
    { bottleneck_strength: 74, supply_chain_control: 72, replaceability: 40, industry_dependency: 68 },
  ),
  company(
    "REGN",
    "Regeneron Pharmaceuticals",
    "Biotech — antibody discovery and Eylea franchise",
    "STRATEGIC ENABLER",
    ["Biotech", "Healthcare"],
    ["biotech", "antibody", "pharma", "clinical", "drug", "platform", "healthcare"],
    why(
      "VelocImmune discovery engine feeds durable specialty pharma franchises.",
      "Therapeutic areas proceed with biosimilars and competing antibodies over time.",
      "Patent cliffs and pipeline hits shift dependence over 2–3 years.",
    ),
    { bottleneck_strength: 76, supply_chain_control: 74, replaceability: 38, industry_dependency: 70 },
  ),
  company(
    "VRTX",
    "Vertex Pharmaceuticals",
    "Biotech — cystic fibrosis and serious disease modalities",
    "STRATEGIC ENABLER",
    ["Biotech", "Healthcare"],
    ["biotech", "pharma", "rare disease", "clinical", "therapy", "healthcare"],
    why(
      "Dominant CF modulation creates high switching costs and reinvestment capacity for new modalities.",
      "Patient populations rely on continued access; pipeline diversification reduces single-franchise risk.",
      "Competing modulators and gene therapies may emerge over long horizons.",
    ),
    { bottleneck_strength: 78, supply_chain_control: 76, replaceability: 36, industry_dependency: 72 },
  ),
  company(
    "ILMN",
    "Illumina",
    "Genomics — sequencing instruments and consumables",
    "CORE BOTTLENECK",
    ["Biotech", "Healthcare"],
    ["sequencing", "genomics", "biotech", "diagnostics", "research", "clinical", "instrument"],
    why(
      "Short-read sequencing installed base locks consumable pull-through for research and clinical labs.",
      "Labs can delay upgrades, but large-scale genomics programs depend on instrument allocation.",
      "PacBio and Oxford Nanopore compete in long-read niches; share shifts slowly.",
    ),
    { bottleneck_strength: 84, supply_chain_control: 82, replaceability: 32, industry_dependency: 80 },
  ),
  company(
    "DXCM",
    "DexCom",
    "Medtech — continuous glucose monitoring",
    "STRATEGIC ENABLER",
    ["Healthcare", "Biotech"],
    ["medtech", "cgm", "diabetes", "device", "healthcare", "wearable", "clinical"],
    why(
      "CGM ecosystem creates recurring sensor pull-through with payer coverage momentum.",
      "Diabetes care continues with fingerstick and pumps without DexCom, but TIR goals favor CGM.",
      "Abbott Libre competes aggressively on price and form factor.",
    ),
    { bottleneck_strength: 77, supply_chain_control: 75, replaceability: 37, industry_dependency: 73 },
  ),
  // —— Defense niche ——
  company(
    "KTOS",
    "Kratos Defense",
    "Defense — drones, hypersonics, and C5ISR",
    "STRATEGIC ENABLER",
    ["Defense", "Space", "Robotics"],
    ["defense", "drone", "uav", "hypersonic", "aerospace", "military", "autonomous"],
    why(
      "Affordable mass and tactical UAS programs depend on specialized subscale prime contractors.",
      "Major programs continue via primes, but niche rapid-development lanes favor Kratos.",
      "Other defense tech vendors bid on overlapping solicitations.",
    ),
    { bottleneck_strength: 76, supply_chain_control: 72, replaceability: 40, industry_dependency: 74 },
  ),
  company(
    "AXON",
    "Axon Enterprise",
    "Defense / public safety — Taser and body-camera cloud",
    "STRATEGIC ENABLER",
    ["Defense", "Platform Software"],
    ["defense", "law enforcement", "saas", "hardware", "security", "public safety", "cloud"],
    why(
      "Integrated hardware + evidence.com cloud creates municipal contract stickiness.",
      "Agencies can use mixed vendors, but bundled Taser/Camera/Records wins RFPs.",
      "Competing body-worn camera vendors substitute on renewals.",
    ),
    { bottleneck_strength: 74, supply_chain_control: 76, replaceability: 41, industry_dependency: 68 },
  ),
  company(
    "NOC",
    "Northrop Grumman",
    "Defense prime — bombers, space, and cyber",
    "STRATEGIC ENABLER",
    ["Defense", "Space"],
    ["defense", "aerospace", "bomber", "space", "military", "prime", "satellite"],
    why(
      "Prime contractor slots on strategic bombers and classified space programs have long qualification.",
      "DoD shifts budgets between primes, but platform choices are decade-long.",
      "Peer primes compete on next-gen awards over multi-year cycles.",
    ),
    { bottleneck_strength: 80, supply_chain_control: 78, replaceability: 34, industry_dependency: 82 },
  ),
  // —— Fintech niche ——
  company(
    "SOFI",
    "SoFi Technologies",
    "Fintech — digital bank and lending platform",
    "STRATEGIC ENABLER",
    ["Fintech", "Platform Software"],
    ["fintech", "bank", "lending", "consumer", "platform", "financial", "payments"],
    why(
      "Integrated bank charter + app engagement lowers CAC for cross-sell lending and deposits.",
      "Consumers can use traditional banks, but niche demographics favor digital-native bundles.",
      "Incumbent banks and neobanks compete on rate promos cyclically.",
    ),
    { bottleneck_strength: 68, supply_chain_control: 66, replaceability: 48, industry_dependency: 64 },
  ),
  company(
    "HOOD",
    "Robinhood Markets",
    "Fintech — retail brokerage and crypto gateway",
    "DOWNSTREAM USER",
    ["Fintech"],
    ["fintech", "brokerage", "retail", "trading", "crypto", "platform", "exchange"],
    why(
      "Retail order flow aggregation influences meme-stock and crypto access dynamics.",
      "Market function continues via traditional brokers; Robinhood is not a structural choke point.",
      "Competing zero-commission apps replicate core features quickly.",
    ),
    { bottleneck_strength: 58, supply_chain_control: 55, replaceability: 55, industry_dependency: 52 },
  ),
  company(
    "AFRM",
    "Affirm",
    "Fintech — BNPL and merchant checkout",
    "DOWNSTREAM USER",
    ["Fintech", "Platform Software"],
    ["fintech", "bnpl", "payments", "consumer", "checkout", "lending", "ecommerce"],
    why(
      "Merchant-embedded BNPL increases conversion but remains one of several payment rails.",
      "Checkout works without BNPL; merchants toggle providers by economics.",
      "PayPal, Klarna, and card issuers substitute readily.",
    ),
    { bottleneck_strength: 56, supply_chain_control: 54, replaceability: 52, industry_dependency: 50 },
  ),
  // —— Industrial automation ——
  company(
    "EMR",
    "Emerson Electric",
    "Industrial automation — process control and valves",
    "STRATEGIC ENABLER",
    ["Robotics", "Energy Materials"],
    ["automation", "industrial", "process", "valve", "control", "manufacturing", "energy"],
    why(
      "Process automation and critical valves gate refinery, LNG, and chemical turnaround schedules.",
      "Plants defer maintenance briefly, but safety-critical swaps require qualified vendors.",
      "Siemens and ABB compete in overlapping automation stacks.",
    ),
    { bottleneck_strength: 77, supply_chain_control: 75, replaceability: 37, industry_dependency: 76 },
  ),
  company(
    "HON",
    "Honeywell",
    "Industrial — aerospace systems, automation, and building controls",
    "STRATEGIC ENABLER",
    ["Robotics", "Defense", "AI Infrastructure"],
    ["industrial", "automation", "aerospace", "building", "control", "manufacturing", "defense"],
    why(
      "Diversified automation and avionics portfolios embed in long-lived industrial and aircraft platforms.",
      "Operators can dual-source some subsystems, but certification cycles favor incumbents.",
      "Peer conglomerates win share on new platform bids over years.",
    ),
    { bottleneck_strength: 75, supply_chain_control: 74, replaceability: 39, industry_dependency: 74 },
  ),
  // —— Storage & climate ——
  company(
    "PSTG",
    "Pure Storage",
    "Storage — flash arrays and AI-ready data platform",
    "STRATEGIC ENABLER",
    ["AI Infrastructure", "Platform Software"],
    ["storage", "flash", "data center", "enterprise", "ai", "software", "array"],
    why(
      "Evergreen storage model and performance tiers target AI training/checkpoint IO profiles.",
      "Hyperscalers self-build; enterprises can use incumbent arrays with tradeoffs.",
      "NetApp and Dell compete on refresh cycles.",
    ),
    { bottleneck_strength: 70, supply_chain_control: 68, replaceability: 44, industry_dependency: 66 },
  ),
  company(
    "OXY",
    "Occidental Petroleum",
    "Oil & CCUS — shale and carbon capture leverage",
    "STRATEGIC ENABLER",
    ["Oil and Gas", "Energy Materials"],
    ["oil", "carbon capture", "ccus", "shale", "hydrocarbon", "energy", "climate"],
    why(
      "Permian footprint plus CCUS ambitions link hydrocarbon cash flow to climate tech scaling.",
      "Energy markets function without OXY CCUS, but policy-linked capture projects depend on operator capacity.",
      "Peer E&Ps and pure-play CCUS ventures compete for sequestration hubs.",
    ),
    { bottleneck_strength: 72, supply_chain_control: 70, replaceability: 42, industry_dependency: 68 },
  ),
  company(
    "MOS",
    "Mosaic Company",
    "Fertilizer — potash and phosphate",
    "STRATEGIC ENABLER",
    ["Agriculture", "Energy Materials"],
    ["fertilizer", "potash", "phosphate", "agriculture", "mining", "food", "crop"],
    why(
      "Potash and phosphate supply influences global crop yield economics and farmer input costs.",
      "Farmers adjust nutrient mixes seasonally, but soil health requires sustained phosphate/potash.",
      "Belarus/Canada supply dynamics and substitutes shift over medium term.",
    ),
    { bottleneck_strength: 78, supply_chain_control: 74, replaceability: 36, industry_dependency: 80 },
  ),
];

export const COMPANY_UNIVERSE_NICHE_COUNT = COMPANY_UNIVERSE_NICHE.length;
