import type { GicsClassification } from "./types";

function gics(
  sector: string,
  industry_group: string,
  industry: string,
  sub_industry: string,
  zh: { sector: string; industry_group: string; industry: string; sub_industry: string },
): GicsClassification {
  return {
    sector,
    industry_group,
    industry,
    sub_industry,
    sector_zh: zh.sector,
    industry_group_zh: zh.industry_group,
    industry_zh: zh.industry,
    sub_industry_zh: zh.sub_industry,
  };
}

/** Curated GICS mapping for the fixed ThroatScan company universe (Phase 0). */
export const TICKER_GICS: Record<string, GicsClassification> = {
  NVDA: gics(
    "Information Technology",
    "Semiconductors & Semiconductor Equipment",
    "Semiconductors",
    "Semiconductors",
    {
      sector: "信息技术",
      industry_group: "半导体与半导体设备",
      industry: "半导体",
      sub_industry: "半导体",
    },
  ),
  AMD: gics(
    "Information Technology",
    "Semiconductors & Semiconductor Equipment",
    "Semiconductors",
    "Semiconductors",
    {
      sector: "信息技术",
      industry_group: "半导体与半导体设备",
      industry: "半导体",
      sub_industry: "半导体",
    },
  ),
  TSM: gics(
    "Information Technology",
    "Semiconductors & Semiconductor Equipment",
    "Semiconductors",
    "Semiconductors",
    {
      sector: "信息技术",
      industry_group: "半导体与半导体设备",
      industry: "半导体",
      sub_industry: "半导体",
    },
  ),
  AVGO: gics(
    "Information Technology",
    "Semiconductors & Semiconductor Equipment",
    "Semiconductors",
    "Semiconductors",
    {
      sector: "信息技术",
      industry_group: "半导体与半导体设备",
      industry: "半导体",
      sub_industry: "半导体",
    },
  ),
  AMAT: gics(
    "Information Technology",
    "Semiconductors & Semiconductor Equipment",
    "Semiconductor Materials & Equipment",
    "Semiconductor Materials & Equipment",
    {
      sector: "信息技术",
      industry_group: "半导体与半导体设备",
      industry: "半导体材料与设备",
      sub_industry: "半导体材料与设备",
    },
  ),
  LRCX: gics(
    "Information Technology",
    "Semiconductors & Semiconductor Equipment",
    "Semiconductor Materials & Equipment",
    "Semiconductor Materials & Equipment",
    {
      sector: "信息技术",
      industry_group: "半导体与半导体设备",
      industry: "半导体材料与设备",
      sub_industry: "半导体材料与设备",
    },
  ),
  ASML: gics(
    "Information Technology",
    "Semiconductors & Semiconductor Equipment",
    "Semiconductor Materials & Equipment",
    "Semiconductor Materials & Equipment",
    {
      sector: "信息技术",
      industry_group: "半导体与半导体设备",
      industry: "半导体材料与设备",
      sub_industry: "半导体材料与设备",
    },
  ),
  TER: gics(
    "Information Technology",
    "Semiconductors & Semiconductor Equipment",
    "Semiconductor Materials & Equipment",
    "Semiconductor Materials & Equipment",
    {
      sector: "信息技术",
      industry_group: "半导体与半导体设备",
      industry: "半导体材料与设备",
      sub_industry: "半导体材料与设备",
    },
  ),
  ANET: gics(
    "Information Technology",
    "Technology Hardware & Equipment",
    "Communications Equipment",
    "Communications Equipment",
    {
      sector: "信息技术",
      industry_group: "技术硬件与设备",
      industry: "通信设备",
      sub_industry: "通信设备",
    },
  ),
  SMCI: gics(
    "Information Technology",
    "Technology Hardware & Equipment",
    "Technology Hardware, Storage & Peripherals",
    "Technology Hardware, Storage & Peripherals",
    {
      sector: "信息技术",
      industry_group: "技术硬件与设备",
      industry: "技术硬件、存储与外围设备",
      sub_industry: "技术硬件、存储与外围设备",
    },
  ),
  MSFT: gics(
    "Information Technology",
    "Software & Services",
    "Software",
    "Systems Software",
    {
      sector: "信息技术",
      industry_group: "软件与服务",
      industry: "软件",
      sub_industry: "系统软件",
    },
  ),
  ORCL: gics(
    "Information Technology",
    "Software & Services",
    "Software",
    "Systems Software",
    {
      sector: "信息技术",
      industry_group: "软件与服务",
      industry: "软件",
      sub_industry: "系统软件",
    },
  ),
  CRM: gics(
    "Information Technology",
    "Software & Services",
    "Software",
    "Application Software",
    {
      sector: "信息技术",
      industry_group: "软件与服务",
      industry: "软件",
      sub_industry: "应用软件",
    },
  ),
  CRWD: gics(
    "Information Technology",
    "Software & Services",
    "Software",
    "Systems Software",
    {
      sector: "信息技术",
      industry_group: "软件与服务",
      industry: "软件",
      sub_industry: "系统软件",
    },
  ),
  SNOW: gics(
    "Information Technology",
    "Software & Services",
    "Software",
    "Application Software",
    {
      sector: "信息技术",
      industry_group: "软件与服务",
      industry: "软件",
      sub_industry: "应用软件",
    },
  ),
  PLTR: gics(
    "Information Technology",
    "Software & Services",
    "Software",
    "Application Software",
    {
      sector: "信息技术",
      industry_group: "软件与服务",
      industry: "软件",
      sub_industry: "应用软件",
    },
  ),
  GOOGL: gics(
    "Communication Services",
    "Media & Entertainment",
    "Interactive Media & Services",
    "Interactive Media & Services",
    {
      sector: "通信服务",
      industry_group: "媒体与娱乐",
      industry: "互动媒体与服务",
      sub_industry: "互动媒体与服务",
    },
  ),
  AMZN: gics(
    "Consumer Discretionary",
    "Consumer Discretionary Distribution & Retail",
    "Broadline Retail",
    "Broadline Retail",
    {
      sector: "可选消费",
      industry_group: "可选消费分销与零售",
      industry: "综合零售",
      sub_industry: "综合零售",
    },
  ),
  EQIX: gics(
    "Real Estate",
    "Equity Real Estate Investment Trusts (REITs)",
    "Specialized REITs",
    "Specialized REITs",
    {
      sector: "房地产",
      industry_group: "股权 REIT",
      industry: "专业 REIT",
      sub_industry: "专业 REIT",
    },
  ),
  VRT: gics(
    "Industrials",
    "Capital Goods",
    "Electrical Equipment",
    "Electrical Components & Equipment",
    {
      sector: "工业",
      industry_group: "资本货物",
      industry: "电气设备",
      sub_industry: "电气部件与设备",
    },
  ),
  ALB: gics(
    "Materials",
    "Materials",
    "Chemicals",
    "Specialty Chemicals",
    {
      sector: "材料",
      industry_group: "材料",
      industry: "化工",
      sub_industry: "特种化学品",
    },
  ),
  TSLA: gics(
    "Consumer Discretionary",
    "Automobiles & Components",
    "Automobiles",
    "Automobile Manufacturers",
    {
      sector: "可选消费",
      industry_group: "汽车与零部件",
      industry: "汽车",
      sub_industry: "汽车制造商",
    },
  ),
  GM: gics(
    "Consumer Discretionary",
    "Automobiles & Components",
    "Automobiles",
    "Automobile Manufacturers",
    {
      sector: "可选消费",
      industry_group: "汽车与零部件",
      industry: "汽车",
      sub_industry: "汽车制造商",
    },
  ),
  F: gics(
    "Consumer Discretionary",
    "Automobiles & Components",
    "Automobiles",
    "Automobile Manufacturers",
    {
      sector: "可选消费",
      industry_group: "汽车与零部件",
      industry: "汽车",
      sub_industry: "汽车制造商",
    },
  ),
  BYDDY: gics(
    "Consumer Discretionary",
    "Automobiles & Components",
    "Automobiles",
    "Automobile Manufacturers",
    {
      sector: "可选消费",
      industry_group: "汽车与零部件",
      industry: "汽车",
      sub_industry: "汽车制造商",
    },
  ),
  APTV: gics(
    "Consumer Discretionary",
    "Automobiles & Components",
    "Automobile Components",
    "Automotive Parts & Equipment",
    {
      sector: "可选消费",
      industry_group: "汽车与零部件",
      industry: "汽车零部件",
      sub_industry: "汽车零部件与设备",
    },
  ),
  CCJ: gics(
    "Energy",
    "Energy",
    "Oil, Gas & Consumable Fuels",
    "Oil & Gas Exploration & Production",
    {
      sector: "能源",
      industry_group: "能源",
      industry: "石油、天然气与可消耗燃料",
      sub_industry: "油气勘探与生产",
    },
  ),
  NEE: gics(
    "Utilities",
    "Utilities",
    "Electric Utilities",
    "Electric Utilities",
    {
      sector: "公用事业",
      industry_group: "公用事业",
      industry: "电力公用事业",
      sub_industry: "电力公用事业",
    },
  ),
  XOM: gics(
    "Energy",
    "Energy",
    "Oil, Gas & Consumable Fuels",
    "Integrated Oil & Gas",
    {
      sector: "能源",
      industry_group: "能源",
      industry: "石油、天然气与可消耗燃料",
      sub_industry: "综合性油气",
    },
  ),
  CVX: gics(
    "Energy",
    "Energy",
    "Oil, Gas & Consumable Fuels",
    "Integrated Oil & Gas",
    {
      sector: "能源",
      industry_group: "能源",
      industry: "石油、天然气与可消耗燃料",
      sub_industry: "综合性油气",
    },
  ),
  SLB: gics(
    "Energy",
    "Energy",
    "Oil, Gas & Consumable Fuels",
    "Oil & Gas Equipment & Services",
    {
      sector: "能源",
      industry_group: "能源",
      industry: "石油、天然气与可消耗燃料",
      sub_industry: "油气设备与服务",
    },
  ),
  LMT: gics(
    "Industrials",
    "Capital Goods",
    "Aerospace & Defense",
    "Aerospace & Defense",
    {
      sector: "工业",
      industry_group: "资本货物",
      industry: "航空航天与国防",
      sub_industry: "航空航天与国防",
    },
  ),
  RTX: gics(
    "Industrials",
    "Capital Goods",
    "Aerospace & Defense",
    "Aerospace & Defense",
    {
      sector: "工业",
      industry_group: "资本货物",
      industry: "航空航天与国防",
      sub_industry: "航空航天与国防",
    },
  ),
  ISRG: gics(
    "Health Care",
    "Health Care Equipment & Services",
    "Health Care Equipment & Supplies",
    "Health Care Equipment",
    {
      sector: "医疗保健",
      industry_group: "医疗保健设备与服务",
      industry: "医疗保健设备与用品",
      sub_industry: "医疗保健设备",
    },
  ),
  UNH: gics(
    "Health Care",
    "Health Care Equipment & Services",
    "Health Care Providers & Services",
    "Managed Health Care",
    {
      sector: "医疗保健",
      industry_group: "医疗保健设备与服务",
      industry: "医疗保健提供商与服务",
      sub_industry: "管理式医疗保健",
    },
  ),
  VEEV: gics(
    "Health Care",
    "Health Care Equipment & Services",
    "Health Care Technology",
    "Health Care Technology",
    {
      sector: "医疗保健",
      industry_group: "医疗保健设备与服务",
      industry: "医疗保健科技",
      sub_industry: "医疗保健科技",
    },
  ),
  LLY: gics(
    "Health Care",
    "Pharmaceuticals, Biotechnology & Life Sciences",
    "Pharmaceuticals",
    "Pharmaceuticals",
    {
      sector: "医疗保健",
      industry_group: "制药、生物科技与生命科学",
      industry: "制药",
      sub_industry: "制药",
    },
  ),
  PFE: gics(
    "Health Care",
    "Pharmaceuticals, Biotechnology & Life Sciences",
    "Pharmaceuticals",
    "Pharmaceuticals",
    {
      sector: "医疗保健",
      industry_group: "制药、生物科技与生命科学",
      industry: "制药",
      sub_industry: "制药",
    },
  ),
  MRK: gics(
    "Health Care",
    "Pharmaceuticals, Biotechnology & Life Sciences",
    "Pharmaceuticals",
    "Pharmaceuticals",
    {
      sector: "医疗保健",
      industry_group: "制药、生物科技与生命科学",
      industry: "制药",
      sub_industry: "制药",
    },
  ),
  V: gics(
    "Financials",
    "Financial Services",
    "Financial Services",
    "Transaction & Payment Processing Services",
    {
      sector: "金融",
      industry_group: "金融服务",
      industry: "金融服务",
      sub_industry: "交易与支付处理服务",
    },
  ),
  MA: gics(
    "Financials",
    "Financial Services",
    "Financial Services",
    "Transaction & Payment Processing Services",
    {
      sector: "金融",
      industry_group: "金融服务",
      industry: "金融服务",
      sub_industry: "交易与支付处理服务",
    },
  ),
  COIN: gics(
    "Financials",
    "Financial Services",
    "Capital Markets",
    "Financial Exchanges & Data",
    {
      sector: "金融",
      industry_group: "金融服务",
      industry: "资本市场",
      sub_industry: "金融交易所与数据",
    },
  ),
  ROK: gics(
    "Industrials",
    "Capital Goods",
    "Machinery",
    "Industrial Machinery & Supplies & Components",
    {
      sector: "工业",
      industry_group: "资本货物",
      industry: "机械",
      sub_industry: "工业机械与零部件",
    },
  ),
};

export function getTickerGics(ticker: string): GicsClassification | undefined {
  return TICKER_GICS[ticker.toUpperCase()];
}

export const TICKER_GICS_COUNT = Object.keys(TICKER_GICS).length;
